logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.learning.eagleeye.*: DEBUG

spring:
  jpa:
    database: PostgreSQL
    show-sql: false
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate.ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/eagleeye_local
    username: postgres
    password: "{cipher}924df29cf1dd92347d499f8fd0ef0f9b30f53cb77fbf89f5d2bfc3254204d441"

  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
  rabbitmq:
    addresses:
      - http://localhost:5672
    username: admin
    password: admin


security:
  oauth2:
    client:
      grant-type: client_credentials
    resource:
      userInfoUri: http://localhost:8901/user

signing:
  key: "{cipher}4c704140eae590379fc1ba34f5878fb855278ee87d2bdc7c99cd8d4c8e0eb93b7da769427fb392535a2bfb37e1de57a8"

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health.showDetails: always

  info:
    git.mode: full

redis:
  host: localhost
  port: 6379
