############## BEGIN CUSTOM CONFIGURATION ##############
signing:
  key: "{cipher}4c704140eae590379fc1ba34f5878fb855278ee87d2bdc7c99cd8d4c8e0eb93b7da769427fb392535a2bfb37e1de57a8"
############## END CUSTOM CONFIGURATION ##############

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.learning.eagleeye.*: DEBUG

spring:
  # Spring Data
  jpa:
    database: PostgreSQL
    show-sql: false
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate.ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/eagleeye_local
    username: postgres
    password: "{cipher}924df29cf1dd92347d499f8fd0ef0f9b30f53cb77fbf89f5d2bfc3254204d441"

  #Spring Cloud
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  zipkin:
    baseUrl: http://localhost:9411

# Spring Security
security:
  oauth2:
    client:
      grant-type: client_credentials
    resource:
      userInfoUri: http://localhost:8901/user

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health.showDetails: always
  info:
    git.mode: full
