spring:
  jpa:
    database: PostgreSQL
    show-sql: false
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate.ddl-auto: create-drop


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/eagleeye_local
    username: postgres
    password: "{cipher}924df29cf1dd92347d499f8fd0ef0f9b30f53cb77fbf89f5d2bfc3254204d441"

security:
  oauth2:
    client:
      grant-type: client_credentials
    resource:
      userInfoUri: http://localhost:8901/user
